# Generated by Django 5.2.8 on 2025-12-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='accesorios/')),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'menu_accesorio',
            },
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bicicletas/')),
                ('tipo', models.CharField(choices=[('mountain', 'Montaña'), ('road', 'Ruta'), ('hybrid', 'Híbrida'), ('bmx', 'BMX'), ('electric', 'Eléctrica'), ('folding', 'Plegable'), ('cruiser', 'Cruiser'), ('city', 'Urbana')], default='city', max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'menu_bicicleta',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='repuestos/')),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('numero_parte', models.CharField(blank=True, max_length=100)),
                ('compatibilidad', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'menu_repuesto',
            },
        ),
    ]
