# Generated by Django 5.2.8 on 2025-12-15 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApiBiciCenter', '0003_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='tipo_producto',
            field=models.CharField(choices=[('bicicleta', 'Bicicleta'), ('repuesto', 'Repuesto'), ('accesorio', 'Accesorio')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('usuario', 'tipo_producto', 'producto_id')},
        ),
    ]
